apiVersion: batch/v1
kind: Job

metadata:
  name: book-catalog-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded

spec:
  template:
    spec:

      imagePullSecrets:
        - name: ghcr-secret

      restartPolicy: Never

      containers:
        - name: migrate

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          command:
            - python
            - manage.py
            - migrate

          envFrom:
            - configMapRef:
                name: book-catalog-api

            - secretRef:
                name: book-catalog-api