# ==================================================
# Secret
# ==================================================
# Stores sensitive application values.
# ==================================================

apiVersion: v1
kind: Secret

metadata:
  name: book-catalog-api

type: Opaque

stringData:

  DB_NAME: book_catalog

  DB_USER: bookuser

  DB_PASSWORD: bookpassword

  DB_HOST: book-catalog-api-postgresql

  DB_PORT: "5432"