# ==================================================
# Secret
# ==================================================
# Stores sensitive application values.
# ==================================================

apiVersion: v1

kind: Secret

metadata:

  # Secret name.
  name: {{ include "book-catalog-api.fullname" . }}

# Secret type.
type: Opaque

stringData:

  # Django secret key.
  DJANGO_SECRET_KEY: "{{ .Values.secret.DJANGO_SECRET_KEY }}"