---
# Source: book-catalog-api/charts/postgresql/templates/primary/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: book-catalog-api-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.10
    app.kubernetes.io/component: primary
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: book-catalog-api
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 5432

---
# Source: book-catalog-api/charts/postgresql/templates/primary/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: book-catalog-api-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.10
    app.kubernetes.io/component: primary
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: book-catalog-api
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary

---
# Source: book-catalog-api/charts/postgresql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: book-catalog-api-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.10
automountServiceAccountToken: false

---
# Source: book-catalog-api/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: book-catalog-api-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.10
type: Opaque
data:
  postgres-password: "SmtjckxoYmZMZQ=="
  password: "Ym9va3Bhc3N3b3Jk"
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords

---
# Source: book-catalog-api/templates/secret.yaml
# ==================================================
# Secret
# ==================================================
# Stores sensitive application values.
# ==================================================

apiVersion: v1
kind: Secret

metadata:
  name: book-catalog-api

type: Opaque

stringData:

  DB_NAME: book_catalog

  DB_USER: bookuser

  DB_PASSWORD: bookpassword

  DB_HOST: book-catalog-api-postgresql

  DB_PORT: "5432"
---
# Source: book-catalog-api/templates/configmap.yaml
# ==================================================
# ConfigMap
# ==================================================
# Stores non-sensitive configuration values.
# ==================================================

apiVersion: v1

kind: ConfigMap

metadata:

  # ConfigMap name.
  name: book-catalog-api

data:

  # Django settings module.
  DJANGO_SETTINGS_MODULE: "bookcatalog.settings"

  # Disable buffered logging.
  PYTHONUNBUFFERED: "1"
---
# Source: book-catalog-api/charts/postgresql/templates/primary/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-api-postgresql-hl
  namespace: "default"
  labels:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.10
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary

---
# Source: book-catalog-api/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-api-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.10
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary

---
# Source: book-catalog-api/templates/service.yaml
# ==================================================
# Service
# ==================================================
# Exposes the Django Pods inside the Kubernetes cluster.
# ==================================================

apiVersion: v1

kind: Service

metadata:

  # Service name.
  name: book-catalog-api

spec:

  # Service type.
  type: ClusterIP

  selector:

    # Forward traffic to Pods with this label.
    app: book-catalog-api

  ports:

  # Service port.
  - port: 80

    # Port exposed by the container.
    targetPort: 8000
---
# Source: book-catalog-api/templates/deployments.yaml
# ==================================================
# Deployment
# ==================================================
# Creates and manages the Django application Pods.
# ==================================================

apiVersion: apps/v1

kind: Deployment

metadata:

  # Deployment name.
  name: book-catalog-api

spec:

  # Number of Pods to run.
  replicas: 2

  selector:

    matchLabels:

      # Match Pods with this label.
      app: book-catalog-api

  template:

    metadata:

      labels:

        # Label assigned to created Pods.
        app: book-catalog-api

    spec:

      # Allows Kubernetes to authenticate with GHCR
      # and pull the private Docker image.
      imagePullSecrets:
        - name: ghcr-secret

      containers:

      - name: django-api

        # Docker image from GHCR.
        image: "ghcr.io/ashford-tulgaa/book-catalog-api:689f975181e32ed666569e8229fff66651d24d57"

        # Image pull behaviour.
        imagePullPolicy: Always

        ports:

        # Django application port.
        - containerPort: 8000

        # Load environment variables from ConfigMap and Secret.
        envFrom:

        - configMapRef:

            name: book-catalog-api

        - secretRef:

            name: book-catalog-api
---
# Source: book-catalog-api/charts/postgresql/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: book-catalog-api-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/instance: book-catalog-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.5.0
    helm.sh/chart: postgresql-16.7.10
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  serviceName: book-catalog-api-postgresql-hl
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: book-catalog-api
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: primary
  template:
    metadata:
      name: book-catalog-api-postgresql
      labels:
        app.kubernetes.io/instance: book-catalog-api
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/version: 17.5.0
        helm.sh/chart: postgresql-16.7.10
        app.kubernetes.io/component: primary
    spec:
      serviceAccountName: book-catalog-api-postgresql
      
      automountServiceAccountToken: false
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: book-catalog-api
                    app.kubernetes.io/name: postgresql
                    app.kubernetes.io/component: primary
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      hostNetwork: false
      hostIPC: false
      containers:
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.5.0-debian-12-r9
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: "/bitnami/postgresql"
            - name: PGDATA
              value: "/bitnami/postgresql/data"
            # Authentication
            - name: POSTGRES_USER
              value: "bookuser"
            - name: POSTGRES_PASSWORD_FILE
              value: /opt/bitnami/postgresql/secrets/password
            - name: POSTGRES_POSTGRES_PASSWORD_FILE
              value: /opt/bitnami/postgresql/secrets/postgres-password
            - name: POSTGRES_DATABASE
              value: "book_catalog"
            # LDAP
            - name: POSTGRESQL_ENABLE_LDAP
              value: "no"
            # TLS
            - name: POSTGRESQL_ENABLE_TLS
              value: "no"
            # Audit
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "false"
            - name: POSTGRESQL_LOG_CONNECTIONS
              value: "false"
            - name: POSTGRESQL_LOG_DISCONNECTIONS
              value: "false"
            - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
              value: "off"
            # Others
            - name: POSTGRESQL_CLIENT_MIN_MESSAGES
              value: "error"
            - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
              value: "pgaudit"
          ports:
            - name: tcp-postgresql
              containerPort: 5432
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "bookuser" -d "dbname=book_catalog" -h 127.0.0.1 -p 5432
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "bookuser" -d "dbname=book_catalog" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
          resources:
            limits:
              cpu: 150m
              ephemeral-storage: 2Gi
              memory: 192Mi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 128Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/postgresql/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/postgresql/tmp
              subPath: app-tmp-dir
            - name: postgresql-password
              mountPath: /opt/bitnami/postgresql/secrets/
            - name: dshm
              mountPath: /dev/shm
            - name: data
              mountPath: /bitnami/postgresql
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: postgresql-password
          secret:
            secretName: book-catalog-api-postgresql
        - name: dshm
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "5Gi"
        

---
# Source: book-catalog-api/templates/migration-job.yaml
apiVersion: batch/v1
kind: Job

metadata:
  name: book-catalog-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded

spec:
  template:
    spec:

      imagePullSecrets:
        - name: ghcr-secret

      restartPolicy: Never

      containers:
        - name: migrate

          image: "ghcr.io/ashford-tulgaa/book-catalog-api:689f975181e32ed666569e8229fff66651d24d57"

          command:
            - python
            - manage.py
            - migrate

          envFrom:
            - configMapRef:
                name: book-catalog-api

            - secretRef:
                name: book-catalog-api
---
# Source: book-catalog-api/templates/ingress.yaml
# ==================================================
# Ingress
# ==================================================
# Routes external HTTP requests to the Django Service.
# ==================================================

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  # Ingress name.
  name: book-catalog-api

spec:

  rules:

  # Hostname for incoming requests.
  - host: bookcatalog.local

    http:

      paths:

      # Route all requests to the application.
      - path: /

        pathType: Prefix

        backend:

          service:

            # Target Service.
            name: book-catalog-api

            port:

              # Service port.
              number: 80
