# GitHub Actions workflow name
name: Book Catalog API CI

# This workflow runs on every push to the main branch and on pull requests targeting main.
permissions:
  contents: write
  packages: write

# When this workflow runs
on:
  # Tells to run on every push to the main branch
  push:
    branches:
      - main

  # Also run when pull requests target main
  pull_request:
    branches:
      - main


jobs:

  build-and-test:

    # Use GitHub's Ubuntu runner
    runs-on: ubuntu-latest

    steps:

      # -------------------------------------------------
      # Step 1: Download repository code
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


      # -------------------------------------------------
      # Step 2: Setup Python environment
      # -------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"


      # -------------------------------------------------
      # Step 3: Install Django dependencies
      # -------------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # -------------------------------------------------
      # Step 4: Prepare Django database
      #
      # CI needs migrations because your API uses models.
      # This creates the SQLite test database.
      # -------------------------------------------------
      - name: Run migrations
        run: |
          python manage.py migrate


      # -------------------------------------------------
      # Step 5: Run Django automated tests
      #
      # If tests fail, Docker image will NOT be built.
      # -------------------------------------------------
      - name: Run tests
        run: |
          python manage.py test


      # -------------------------------------------------
      # Step 6: Login to GitHub Container Registry
      #
      # Uses a Personal Access Token stored as a GitHub Secret.
      # The actual token is NOT stored in this file.
      # -------------------------------------------------
      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Ashford-tulgaa
          password: ${{ secrets.BOOK_CATALOG_API_SECRET}}


      # -------------------------------------------------
      # Step 7: Build Docker image
      #
      # Uses commit SHA as immutable image tag.
      # Example:
      # book-catalog-api:a83f92d1
      # -------------------------------------------------
      - name: Build Docker image
        if: github.event_name == 'push'
        run: |
          docker build \
          -t ghcr.io/ashford-tulgaa/book-catalog-api:${{ github.sha }} .


      # -------------------------------------------------
      # Step 8: Push Docker image to GHCR
      #
      # Kubernetes will pull this exact image tag.
      # -------------------------------------------------
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push \
          ghcr.io/ashford-tulgaa/book-catalog-api:${{ github.sha }}


      # -------------------------------------------------
      # Step 9: Update Helm values
      #
      # Changes:
      # tag: latest
      #
      # into:
      # tag: <commit-sha>
      # -------------------------------------------------
      - name: Update Helm image tag
        if: github.event_name == 'push'
        run: |
          sed -i "s/tag:.*/tag: ${{ github.sha }}/" \
          book-catalog-api/values.yaml


      # -------------------------------------------------
      # Step 10: Commit Helm change
      #
      # Argo CD watches Git.
      # This commit triggers deployment.
      # -------------------------------------------------
      - name: Commit Helm update
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add book-catalog-api/values.yaml

          git commit -m "Update image tag to ${{ github.sha }}" || exit 0

          git push